project:
  type: website
  output-dir: "docs"
website:
  title: "Minimal Effort Tables in Quarto"
  # author: "Sally A.M. Hogenboom"
  # DATE
  # date: today # applied when book is rendered
  #date-format: "D MMMM, YYYY" # 21st of March, 2022
  # OUTPUT FORMAT
  # Extention added after generating the required format (e.g., OpenMenS.pdf)
  # output-file: "QuartoTableOverview"
  # CONTENT
  navbar:
    left:
     - href: overview.html
       text: "HTML"
     - href: overview.pdf
       text: "PDF"

format:
  html:
    theme: cosmo
    toc-location: left
    minimal: true
  pdf:
    documentclass: scrreprt

