# Objective {.unnumbered}

This is an exploration of 'out-of-the-box' tables in Quarto, also known as tables for lazy people. I compare the available packages to see which minimal effort tables one can produce in HTML and PDF output. Please note that this overview is primarily an implementation of packages discussed in the [RMarkdown Cookbook](https://bookdown.org/yihui/rmarkdown-cookbook/table-other.html).

To showcase the different tables we use the [palmerpenguins](https://allisonhorst.github.io/palmerpenguins/) data - because who doesn't love penguins? It is by design that I used a dataset with too many columns to fit a single page. HTML output generally resolves the issues by creating slider divs, whereas PDF output at times struggles in unexpected ways. I believe it is good to see where issues may arise with these 'out-of-the-box' solutions.

I've also included cross-references to the tables because `Quarto` uses a different formatting for [cross-referencing](https://quarto.org/docs/authoring/cross-references.html) than `RMarkdown`. Unfortunately, this causes some unexpected cases in which cross-referencing does not yet work. 
